const actionTypes = {
  FETCH_REQUEST_POSTS: 'FETCH_REQUEST_POSTS',
  FETCH_SUCCESS_POSTS: 'FETCH_SUCCESS_POSTS',
  FETCH_ERROR_POSTS: 'FETCH_ERROR_POSTS',
  FETCH_REQUEST_POST: 'FETCH_REQUEST_POST',
  FETCH_SUCCESS_POST: 'FETCH_SUCCESS_POST',
  FETCH_ERROR_POST: 'FETCH_ERROR_POST',
  FETCH_REQUEST_COMMENT: 'FETCH_REQUEST_COMMENT',
  FETCH_SUCCESS_COMMENT: 'FETCH_SUCCESS_COMMENT',
  FETCH_ERROR_COMMENT: 'FETCH_ERROR_COMMENT',
  FETCH_REQUEST_DELETE_POST: 'FETCH_REQUEST_DELETE_POST',
  FETCH_SUCCESS_DELETE_POST: 'FETCH_SUCCESS_DELETE_POST',
  FETCH_ERROR_DELETE_POST: 'FETCH_ERROR_DELETE_POST',
};

export default actionTypes;
